### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by tomtom87** [saucelabs-sample-scripts/Node-Appium#1]
Please can you explain how to use this with the sauce labs tunnel connect, I am using mocha for my test framework. Script is below:

```

var wd = require('wd'),
    desiredCaps = {
        browserName: '',
        appiumVersion: '1.4.16',
        deviceName: 'Samsung Galaxy S4 Emulator',
        platformVersion: '4.4',
        platformName: 'Android',
        name: 'Pressie Android Test Suite',
        app: '/home/qa/pressie-qa.apk'
    },
    driver = wd.remote("ondemand.saucelabs.com", 80, "username", "key");


describe("Pressie Test Suite", function () {
    before(function () {
      return driver.init(desiredCaps, function(error) {
          if (error) {
              throw new Error('Session did not start properly. Please make sure you sauce credentials are correct');
          }
          driver.quit();
      });
    });

    it("should login with Mobile OTP", function () {
      var testNumber = "8787878787";
      var testPass   = "123456";
      return driver
        .elementByXPath('//android.widget.Button[@resource-id="jaarwis.pressie:id/fragment_login_chooser_button_signin"]')
        .should.eventually.exist
        .click()
        .elementByXPath('//android.widget.Button[@resource-id="jaarwis.pressie:id/fragment_signin_chooser_button_signin"]')
        .should.eventually.exist
        .click()
        .elementByXPath('//android.widget.TextView[@resource-id="jaarwis.pressie:id/editText10"]')
        .should.eventually.exist
        .click()
        .elementByXPath('//android.widget.TextView[@text=\'H\']')
        .click()
        .elementByXPath('//android.widget.TextView[@text=\'+852\']')
        .click()
        .elementByXPath('//android.widget.EditText[@resource-id="jaarwis.pressie:id/fragment_sign_in_sign_up_edittext_email1"]')
        .sendKeys(testNumber)
        .elementByXPath('//android.widget.EditText[@resource-id="jaarwis.pressie:id/fragment_sign_in_sign_up_edittext_password1"]')
        .sendKeys(testPass)
        .elementByXPath('//android.widget.Button[@resource-id="jaarwis.pressie:id/fragment_sign_in_sign_up_button_signin"]')
        .click();
    });

});

```

I have the tunnel open in another shell on the same server

```
10 Feb 04:08:36 - Resolving tunnel hostname to 162.222.79.63 took 237ms.
10 Feb 04:08:36 - Starting Selenium listener...
10 Feb 04:08:36 - Establishing secure TLS connection to tunnel...
10 Feb 04:08:36 - Selenium listener started on port 4445.
10 Feb 04:08:38 - Sauce Connect is up, you may start your tests.
```

When I run the tests, the `driver.init` appears to work (there is no error) but I get the following output:

```
TypeError: Cannot read property 'should' of undefined
      at Context.<anonymous> (pressie-sauce.js:29:9)
```

Meaning the driver is not working correctly, please assist as I would like to use the sauce labs account I am paying for. Thank you :+1:

**Comment by DrPhilG** [comment]
Hi Tom, you should consult our documentation wiki https://wiki.saucelabs.com/ for more information about Sauce Connect and running tests. If you have further questions you can also contact our support team through the form on this page: https://support.saucelabs.com/customer/portal/emails/new https://support.saucelabs.com/customer/portal/emails/new

Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com mailto:philg@saucelabs.com
Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/

**Comment by tomtom87** [comment]
I've done both, there are countless comments there asking for help and a more comprehensive example of how to make it work. 

You have not answered my question at all. 

I have submitted a support ticket also which has not been reviewed. I have followed your (to be completely honest very inadequate) documentation and that brought me to open a issue here as the code is not working.

Considering this is a paid service and you are a guy with a PhD I am very disappointed that the customer service is below par to even open source projects. I am paying for this and it does not work at all. You don't even attempt at a solution... I need this working. Please answer the question instead of passing the buck.

Peace

**Comment by tomtom87** [comment]
Dear Dr Phil,

The link is dead in your documentation so I cannot find out any more unfortunately, but I am hoping you will reply soon with an answer this...

Very confused, managed to find a configurator in your documentation but it is reported as broken by a user and the link for the android part is a dead link...

Thanks

**Comment by DrPhilG** [comment]
Hi Tom, 

I’ve forwarded your comments to both the test automation engineer who wrote the node.js script, and our Director of Support regarding your unanswered ticket.

The Platform Configurator link is working as expected for me. We did have a problem on Friday the 5th, but resolved it within a few hours. If the link isn’t working for you still, please let me know so I can investigate.

The documentation is very much a work-in-progress, as there was no active management of it until I joined the company about six months ago. I’m currently working on a substantial revision of the content that I hope will be ready by early Q2, if not by the end of the quarter. If you have suggestions for improvements or topics that aren’t currently covered that would be useful to you, please let me know.

Phil 

Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com mailto:philg@saucelabs.com
Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/

**Comment by tomtom87** [comment]
The platform configurator is leading me to a dead link I dont get 
anything from it Phil... please can you give me your URL you are using 
for that?

Ok well please check the documentation soon as currently this is 
completely unusable and there are complaints on every page I looked at.

I look forward to hearing back from the automation engineer then, will 
the reply be on this thread?

All the best

On 11/02/2559 BE 11:55 p.m., DrPhilG wrote:

> Hi Tom,
> 
> I’ve forwarded your comments to both the test automation engineer who 
> wrote the node.js script, and our Director of Support regarding your 
> unanswered ticket.
> 
> The Platform Configurator link is working as expected for me. We did 
> have a problem on Friday the 5th, but resolved it within a few hours. 
> If the link isn’t working for you still, please let me know so I can 
> investigate.
> 
> The documentation is very much a work-in-progress, as there was no 
> active management of it until I joined the company about six months 
> ago. I’m currently working on a substantial revision of the content 
> that I hope will be ready by early Q2, if not by the end of the 
> quarter. If you have suggestions for improvements or topics that 
> aren’t currently covered that would be useful to you, please let me know.
> 
> Phil
> 
> Phil Gochenour, PhD
> Senior Technical Writer
> philg@saucelabs.com mailto:philg@saucelabs.com
> Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/
> 
> > On Feb 11, 2016, at 12:29 AM, Tom Whitbread 
> > notifications@github.com wrote:
> > 
> > Dear Dr Phil,
> > 
> > The link is dead in your documentation so I cannot find out any more 
> > unfortunately, but I am hoping you will reply soon with an answer this...
> > 
> > Very confused, managed to find a configurator in your documentation 
> > but it is reported as broken by a user and the link for the android 
> > part is a dead link...
> > 
> > Thanks
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182761455.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182957053.

## 

## 

Tom Whitbread
Gript.co.uk

**Comment by DrPhilG** [comment]
https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

Are you using the link in the left-hand navigation of the wiki, or something different?

I expect the SE will reply on this thread, but may be otherwise engaged at the moment. 

Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com mailto:philg@saucelabs.com
Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/

**Comment by tomtom87** [comment]
Yh i use this link Phil but it's not generate the settings for me it just sends me to home page...

**Comment by DrPhilG** [comment]
I’m not certain what’s happening here that the link doesn't work for you. I’ve asked some other people in different locations to try it, and they all verify that it’s working as expected - it takes them to the PC page, and from there they can use the selection menus to generate the desired caps. Just to make sure I clearly understand what’s happening, when you click this link https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/, it drops you on the homepage of the wiki? And if you use the Platform Configurator link in the left-hand nav of the DOCS wiki, it does the same thing? If that’s the case, can you tell me the platform/OS/browser that you’re using so I can investigate further?

Phil

Phil Gochenour, PhD
Senior Technical Writer 
philg@saucelabs.com mailto:philg@saucelabs.com
Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/

**Comment by jeansandberg** [comment]
Hi Tom,

I can see you're not having a great experience. I've been there and that's no fun.

I searched for a support ticket in the Sauce Labs Customer Support but don't see one. How/where did you open a support request?

Best,
Jean Sandberg
Director of Customer Support
Sauce Labs

**Comment by tomtom87** [comment]
Hi Phil,

Ok to clarify. I can load the page yes, but when i try to generate the 
caps it just sends me back to the home page of the wiki that's why I say 
its a dead link because I cannot generate anything

I'm on Mac OSX 10.11 El Capitan using Chromium

The link on the left works yes, the url work yes, but try and use the 
actual tool I got no output

Also doesn't seem to be anywhere explaining anymore about the .apk 
upload or how to do that?

Cheers

On 12/02/2559 BE 12:30 a.m., DrPhilG wrote:

> I’m not certain what’s happening here that the link doesn't work for 
> you. I’ve asked some other people in different locations to try it, 
> and they all verify that it’s working as expected - it takes them to 
> the PC page, and from there they can use the selection menus to 
> generate the desired caps. Just to make sure I clearly understand 
> what’s happening, when you click this link 
> https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ 
> https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/, it 
> drops you on the homepage of the wiki? And if you use the Platform 
> Configurator link in the left-hand nav of the DOCS wiki, it does the 
> same thing? If that’s the case, can you tell me the 
> platform/OS/browser that you’re using so I can investigate further?
> 
> Phil
> 
> Phil Gochenour, PhD
> Senior Technical Writer
> philg@saucelabs.com mailto:philg@saucelabs.com
> Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/
> 
> > On Feb 11, 2016, at 9:14 AM, Tom Whitbread 
> > notifications@github.com wrote:
> > 
> > Yh i use this link Phil but it's not generate the settings for me it 
> > just sends me to home page...
> > 
> > Sent from my iPhone
> > 
> > > On 12 Feb 2016, at 00:09, DrPhilG notifications@github.com wrote:
> > > 
> > > https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/ 
> > > https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/
> > > 
> > > Are you using the link in the left-hand navigation of the wiki, or 
> > > something different?
> > > 
> > > I expect the SE will reply on this thread, but may be otherwise 
> > > engaged at the moment.
> > > 
> > > Phil Gochenour, PhD
> > > Senior Technical Writer
> > > philg@saucelabs.com mailto:philg@saucelabs.com
> > > Sauce Labs http://saucelabs.com/ | Sauce blog http://sauceio.com/
> > > 
> > > > On Feb 11, 2016, at 9:01 AM, Tom Whitbread 
> > > > notifications@github.com wrote:
> > > > 
> > > > The platform configurator is leading me to a dead link I dont get
> > > > anything from it Phil... please can you give me your URL you are 
> > > > using
> > > > for that?
> > > > 
> > > > Ok well please check the documentation soon as currently this is
> > > > completely unusable and there are complaints on every page I 
> > > > looked at.
> > > > 
> > > > I look forward to hearing back from the automation engineer 
> > > > then, will
> > > > the reply be on this thread?
> > > > 
> > > > All the best
> > > > 
> > > > On 11/02/2559 BE 11:55 p.m., DrPhilG wrote:
> > > > 
> > > > > Hi Tom,
> > > > > 
> > > > > I’ve forwarded your comments to both the test automation 
> > > > > engineer who
> > > > > wrote the node.js script, and our Director of Support 
> > > > > regarding your
> > > > > unanswered ticket.
> > > > > 
> > > > > The Platform Configurator link is working as expected for me. 
> > > > > We did
> > > > > have a problem on Friday the 5th, but resolved it within a few 
> > > > > hours.
> > > > > If the link isn’t working for you still, please let me know so 
> > > > > I can
> > > > > investigate.
> > > > > 
> > > > > The documentation is very much a work-in-progress, as there 
> > > > > was no
> > > > > active management of it until I joined the company about six 
> > > > > months
> > > > > ago. I’m currently working on a substantial revision of the 
> > > > > content
> > > > > that I hope will be ready by early Q2, if not by the end of the
> > > > > quarter. If you have suggestions for improvements or topics that
> > > > > aren’t currently covered that would be useful to you, please 
> > > > > let me know.
> > > > > 
> > > > > Phil
> > > > > 
> > > > > Phil Gochenour, PhD
> > > > > Senior Technical Writer
> > > > > philg@saucelabs.com mailto:philg@saucelabs.com
> > > > > Sauce Labs http://saucelabs.com/ | Sauce blog 
> > > > > http://sauceio.com/
> > > > > 
> > > > > > On Feb 11, 2016, at 12:29 AM, Tom Whitbread
> > > > > > notifications@github.com wrote:
> > > > > > 
> > > > > > Dear Dr Phil,
> > > > > > 
> > > > > > The link is dead in your documentation so I cannot find out 
> > > > > > any more
> > > > > > unfortunately, but I am hoping you will reply soon with an 
> > > > > > answer this...
> > > > > > 
> > > > > > Very confused, managed to find a configurator in your 
> > > > > > documentation
> > > > > > but it is reported as broken by a user and the link for the 
> > > > > > android
> > > > > > part is a dead link...
> > > > > > 
> > > > > > Thanks
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > 
> > > > > https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182761455.
> > > > > 
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > 
> > > > > https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182957053.
> > > > 
> > > > ## 
> > > > 
> > > > ## 
> > > > 
> > > > Tom Whitbread
> > > > Gript.co.uk
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub 
> > > > https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182958716.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub 
> > > https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182963190.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182967698.

## 

## 

Tom Whitbread
Gript.co.uk

**Comment by tomtom87** [comment]
Thanks Jean yeh its not much fun at the moment

I opened a support ticket in the Saucelabs support I just got a reply on 
it, I was told it 'works fine'. I really am happy it works for you guys 
but it doesnt at all for me. So I think there is some break down on 
communication over what steps it takes to instantiate the test properly.

Ticket URL: 
https://support.saucelabs.com/customer/portal/private/cases/36013

Some more information would be greatly appreciated.

On 12/02/2559 BE 1:11 a.m., jeansandberg wrote:

> Hi Tom,
> 
> I can see you're not having a great experience. I've been there and 
> that's no fun.
> 
> I searched for a support ticket in the Sauce Labs Customer Support but 
> don't see one. How/where did you open a support request?
> 
> Best,
> Jean Sandberg
> Director of Customer Support
> Sauce Labs
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-182984134.

## 

## 

Tom Whitbread
Gript.co.uk

**Comment by ndmanvar** [comment]
Hi Tom,

You cannot specify an absolute path to apk that is on your local file system.

You must either:
1. upload to sauce storage, and then reference using sauce-storage:x.apk
      See:  https://wiki.saucelabs.com/display/DOCS/Using+Sauce+Storage+for+Test+Assets
2. have the apk open to public. i.e. on aws and then reference it using http://aws.com/x.apk

**Comment by tomtom87** [comment]
Thanks for the reply :)

Yeh I figured this out after some trial and error, got the sauce-storage 
apk working now, the problem I have now is that the test only runs for 
50 seconds. I watch the video, the emulator loads but the app is not 
present on the device. The emulator doesn't start the app niether. 
Appium logs just stop, there is no error.

These tests I have verified running locally on several machines (Mac OSX 
and Debian / Ubuntu desktops) they worked flawlessly. Please can you 
assist as to why saucelabs is not able to work correctly?

All the best

On 17/02/2559 BE 12:34 a.m., Neil Manvar wrote:

> Hi Tom,
> 
> You cannot specify an absolute path to apk that is on your local file 
> system.
> 
> You must either:
> 1. upload to sauce storage, and then reference using sauce-storage:x.apk
> See: 
> https://wiki.saucelabs.com/display/DOCS/Using+Sauce+Storage+for+Test+Assets
> 2. have the apk open to public. i.e. on aws and then reference it 
> using http://aws.com/x.apk
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/saucelabs-sample-scripts/Node-Appium/issues/1#issuecomment-184789551.

## 

## 

Tom Whitbread
Gript.co.uk

**Comment by tomtom87** [comment]
Giving up on saucelabs and using AWS instead. Service sucks constantly offline and having problems, total headache to use and basically a unfinished product they are trying to sell. Epic Fail.
